services:
  kafka-1: # these services look complicated, theyre really not, i'll comment the first broker and the rest are kinda the same
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller # we set this to be both a broker and controller (look up KRaft if your interested). it makes everything easier
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093 # other nodes on control plane
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093 # defining where data should be sent
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092 # defining which port clients can autodetect
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER # name of controller interface (see CONTROLLER://:9093 above?)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT # say we will communicate in plaintest on both planes (for simplicity)
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT # name of listener interface
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk" # each broker needs cluster id (can be totally random)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2 # set replication to two so each node is backed up on other node (so we dont lose consumer state on failure)
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2 # replication for producers and exactly-once processing
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 # in sync replicas, which are eligible for promotion if current leader dies
    volumes:
      - kafka1_data:/bitnami/kafka # persist data

  kafka-2:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-2
    hostname: kafka-2
    ports:
      - "9094:9092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka2_data:/bitnami/kafka

  kafka-3:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-3
    hostname: kafka-3
    ports:
      - "9095:9092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka3_data:/bitnami/kafka

  kafka-ui: # ui because it exists so why not!
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=walmart-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  producer-online:
    build: ./producers/online
    container_name: producer-online
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - TRAFFIC_MODE=NORMAL

  producer-warehouse:
    build: ./producers/warehouse
    container_name: producer-warehouse
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - TRAFFIC_MODE=NORMAL

  producer-retail:
    build: ./producers/retail
    container_name: producer-retail
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - TRAFFIC_MODE=NORMAL

#  processor:
#    build: ./processor
#    container_name: processor
#    depends_on:
#      - kafka-1
#    environment:
#      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
#
#  consumer:
#    build: ./consumer
#    container_name: consumer
#    depends_on:
#      - kafka-1
#    environment:
#      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092,kafka-3:9092

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data: